apis:
  - name: gitlab
    spec_url: https://gitlab.example.com/api/graphql
    base_url_override: https://gitlab.example.com/api/graphql
    
    # Enable GraphQL CRUD grouping optimization
    optimization:
      enable_crud_grouping: true
      flatten_inputs: false
      response_mode: essential
