apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skyline-mockingbird
  namespace: skyline
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: REDACTED_BEARER_SHORT.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: skyline-mockingbird
            port:
              number: 80
